### ISSUE TITLE
Why is publishing on the same channel thread while consuming a problem?

### ISSUE THREAD

**Issue by arnauorriols** [hreinhardt/amqp#84]
Hi,

I understand the solution of forking a new thread to do any complex consuming that involves further using the channel where we are consuming messages. What I don't fully understand is the reason why this is needed. 

I understand it has to do with deadlocking the channel. In the case of publishing a new message, the operation might block if the channel is in flow mode. But why would this be a deadlock? Is it because the channel thread is blocked and thus it cannot receive the signal to be released from flow mode? Or is it a more subtle internal thing? Or is it just that other consumers from the same channel would get blocked, which is generally something you wouldn't want, but not necessarily a deadlock?

Thank you for your time!

**Comment by hreinhardt** [comment]
(I have to admit that I don't really remember the details myself, so I did a short look into the source; hopefully my explanation is correct.)

The issue is basically a deadlock. The reason has to do with how the library handles incoming messages from the server.

Every channel has a single `channelReceiver` loop that handles incoming messages; these can be both asynchronous messages from the server (e.g. messages from some AMQP exchange) as well as synchronous messages (responses to requests from the client). 

It is vital that the `channelReceiver` never becomes blocked, as it would be unable to process incoming synchronous messages, i.e. requests couldn't be processed anymore.

But since the `consumeMsgs` callbacks are running inside `channelReceiver`, if you perform a request, it will block (waiting for its response) the `channelReceiver` which in turn will be unable to actually handle the response to that request.

**Comment by arnauorriols** [comment]
Right. And the reason publishMsg is not in the list of safe operations is the [waitLock of the writeAssembly](https://github.com/hreinhardt/amqp/blob/9caebebec04f510046ce74a79efa97fcd194bb29/Network/AMQP/Internal.hs#L772)

Cool, thanks!
