### ISSUE TITLE
Add withConnection function

### ISSUE THREAD

**Issue by supersven** [hreinhardt/amqp#95]
Lately I've worked a lot with RabbitMQ, unfortunately with Kotlin/Arrow. One "pattern"* that proved to be very useful are `with...` functions that make sure connections (and channels in Kotlin) are closed automatically under all circumstances.
This reduces boilerplate and hides the connection management logic from the user.

`http-client` uses this approach to handle connections, too: https://hackage.haskell.org/package/http-client-0.7.4/docs/Network-HTTP-Client.html#v:withConnection

`withConnection` for ampq could look like `withConnection :: String -> Text -> Text -> Text -> (Connection -> IO a) -> IO a`.

One could go even one step further and define `withConnectedChannel :: String -> Text -> Text -> Text -> (Channel -> IO a) -> IO a`, assuming that most users work with one connection and one channel.

I would happily volunteer to implement this, but thought it might make sense to first discuss this topic.

*) Unfortunately I don't know how it's really called.

**Comment by hreinhardt** [comment]
I'm undecided on this proposal. I think it could be confusing to users when they use it in conjunction with `consumeMsgs`. Consider something like this:

```haskell
main =
    withConnection "host" "vhost" "name" "pass" $ \conn ->
        withChannel conn $ \chan ->
            consumeMsgs chan "queue" Ack $ \_ -> return ()
```

Since the connection and channel would be opened and immediately closed, the `consumeMsgs` callback would never be executed. So the proposed `withX`-functions would only be useful if you're only sending messages. My fear is that we would be guiding the user into structuring his application in a way that doesn't really make sense for a lot of use-cases.

Are you working on a real-world AMQP codebase where you could verify that these functions would actually make your life easier?

**Comment by supersven** [comment]
Hey @hreinhardt ,
 
Good point.

Indeed, listeners/callbacks don't fit to this approach. :thinking: 

This idea actually comes from a real-world project; unfortunately in Kotlin/Arrow with the Java client library. There we're using `basicPublish` to send and `basicGet` to receive.

I'm closing this issue because I think you're right - I just haven't thought about listeners when I opened this ticket.
Thanks for your fast and detailed response.

**Comment by hreinhardt** [comment]
Anyway, thanks for bringing up the idea.

Out of curiosity: Why are you using basicGet instead of basicConsume in Kotlin?

**Comment by supersven** [comment]
Well, it turned out that there was no good reason to poll with `basicGet` as the usages we had can be replaced by a mutable list and a consumer writing to it. (The main usage was to check if messages were sent in tests.)

Thanks helping me reconsider this 😄
